### ISSUE TITLE
Version dependency mismatch with base-4.7.0.0 (ghc 7.8.4)

### ISSUE THREAD

**Issue by hjarvi** [mgajda/posix-realtime#1]
Due to the requirement of unix < 2.7, posix-realtime does not get dependencies satisfied with base-4.7.0.0 (and ghc 7.8.4) as unix 2.6.\* depend on base <4.7.

I was able to get posix-realtime to work for me with base-4.7.0.0 with the following change:

commit 2afe312a7b6cb95d58a139f03b1ff046676910ba
Author: Harri Järvi harri.jarvi@atostek.com
Date:   Wed Mar 25 12:07:38 2015 +0200

```
posix-realtime: updated library dependencies so that it is compatible with base-4.7.0.0 and ghc 7.8.4.
```

diff --git a/posix-realtime.cabal b/posix-realtime.cabal
index f59a801..8b3c729 100644
--- a/posix-realtime.cabal
+++ b/posix-realtime.cabal
@@ -1,5 +1,5 @@
 name:          posix-realtime
-version:       0.0.0.2
+version:       0.0.0.3
 license:       BSD3
 license-file:  LICENSE
 category:       System
@@ -29,7 +29,7 @@ library
                   System.Posix.Realtime.RTDataTypes
                   System.Posix.Realtime.RTTime
                   System.Posix.Realtime.Aio
-  build-depends:  base > 4.5 && < 4.8, unix < 2.7
-  build-depends:  base > 4.5 && < 4.8, unix
  extensions:  CPP, ForeignFunctionInterface
  include-dirs:        include
  install-includes:

**Comment by mgajda** [comment]
Will fix it in overnight Thanks a lot for the report!

On Monday, April 27, 2015, hjarvi notifications@github.com wrote:

> Due to the requirement of unix < 2.7, posix-realtime does not get
> dependencies satisfied with base-4.7.0.0 (and ghc 7.8.4) as unix 2.6.*
> depend on base <4.7.
> 
> I was able to get posix-realtime to work for me with base-4.7.0.0 with the
> following change:
> 
> commit 2afe312a7b6cb95d58a139f03b1ff046676910ba
> Author: Harri Järvi harri.jarvi@atostek.com
> <javascript:_e(%7B%7D,'cvml','harri.jarvi@atostek.com');>
> Date: Wed Mar 25 12:07:38 2015 +0200
> 
> posix-realtime: updated library dependencies so that it is compatible with base-4.7.0.0 and ghc 7.8.4.
> 
> diff --git a/posix-realtime.cabal b/posix-realtime.cabal
> index f59a801..8b3c729 100644
> --- a/posix-realtime.cabal
> +++ b/posix-realtime.cabal
> @@ -1,5 +1,5 @@
> name: posix-realtime
> -version: 0.0.0.2
> +version: 0.0.0.3
> license: BSD3
> license-file: LICENSE
> category: System
> @@ -29,7 +29,7 @@ library
> System.Posix.Realtime.RTDataTypes
> System.Posix.Realtime.RTTime
> System.Posix.Realtime.Aio
> - build-depends: base > 4.5 && < 4.8, unix < 2.7
> - build-depends: base > 4.5 && < 4.8, unix extensions: CPP,
>   ForeignFunctionInterface include-dirs: include install-includes:
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/mgajda/posix-realtime/issues/1.

## 

  Pozdrawiam
    Michał

**Comment by hjarvi** [comment]
Pull request at https://github.com/mgajda/posix-realtime/pull/2

**Comment by hjarvi** [comment]
Thanks for merging.
I'd like to see this fix uploaded to Hackage soon.

**Comment by mgajda** [comment]
Sorry it took so long Jarvi.

**Comment by mgajda** [comment]
I mean: I've just uploaded updated version for GHC 7.10 to the Hackage.
If you use this package too, I may add it to Stackage for the next round.
